// @flow

export const GET_ADMIN_TOURNAMENTS = 'GET_ADMIN_TOURNAMENTS'
export const GET_JUDGE_TOURNAMENT = 'GET_JUDGE_TOURNAMENT'
export const GET_SINGLE_TOURNAMENT = 'GET_SINGLE_TOURNAMENT'
export const GET_ALL_TOURNAMENTS = 'GET_ALL_TOURNAMENTS'


export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_USER = 'LOGIN_USER'

export const GET_ACCESS_KEYS = 'GET_ACCESS_KEYS'

export const CREATE_TOURNAMENT = 'CREATE_TOURNAMENT'
