language: node_js

services:
  - "docker"

node_js:
  - "node"

script:
  - "npm run test"
  - "npm run lint"
  - "npm run build"

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_SECRET";
    docker build -t 4temps .;
    docker tag 4temps:latest kindstrom/4temps:latest;
    docker push kindstrom/4temps:latest;

cache:
  directories:
    - "node_modules"