// flow-typed signature: 276ce2202e6aeb739f67ed8f5878014c
// flow-typed version: <<STUB>>/helmet_v^4.2.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'helmet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'helmet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'helmet/dist' {
  declare module.exports: any;
}

declare module 'helmet/dist/middlewares/content-security-policy' {
  declare module.exports: any;
}

declare module 'helmet/dist/middlewares/expect-ct' {
  declare module.exports: any;
}

declare module 'helmet/dist/middlewares/referrer-policy' {
  declare module.exports: any;
}

declare module 'helmet/dist/middlewares/strict-transport-security' {
  declare module.exports: any;
}

declare module 'helmet/dist/middlewares/x-content-type-options' {
  declare module.exports: any;
}

declare module 'helmet/dist/middlewares/x-dns-prefetch-control' {
  declare module.exports: any;
}

declare module 'helmet/dist/middlewares/x-download-options' {
  declare module.exports: any;
}

declare module 'helmet/dist/middlewares/x-frame-options' {
  declare module.exports: any;
}

declare module 'helmet/dist/middlewares/x-permitted-cross-domain-policies' {
  declare module.exports: any;
}

declare module 'helmet/dist/middlewares/x-powered-by' {
  declare module.exports: any;
}

declare module 'helmet/dist/middlewares/x-xss-protection' {
  declare module.exports: any;
}

// Filename aliases
declare module 'helmet/dist/index' {
  declare module.exports: $Exports<'helmet/dist'>;
}
declare module 'helmet/dist/index.js' {
  declare module.exports: $Exports<'helmet/dist'>;
}
declare module 'helmet/dist/middlewares/content-security-policy/index' {
  declare module.exports: $Exports<'helmet/dist/middlewares/content-security-policy'>;
}
declare module 'helmet/dist/middlewares/content-security-policy/index.js' {
  declare module.exports: $Exports<'helmet/dist/middlewares/content-security-policy'>;
}
declare module 'helmet/dist/middlewares/expect-ct/index' {
  declare module.exports: $Exports<'helmet/dist/middlewares/expect-ct'>;
}
declare module 'helmet/dist/middlewares/expect-ct/index.js' {
  declare module.exports: $Exports<'helmet/dist/middlewares/expect-ct'>;
}
declare module 'helmet/dist/middlewares/referrer-policy/index' {
  declare module.exports: $Exports<'helmet/dist/middlewares/referrer-policy'>;
}
declare module 'helmet/dist/middlewares/referrer-policy/index.js' {
  declare module.exports: $Exports<'helmet/dist/middlewares/referrer-policy'>;
}
declare module 'helmet/dist/middlewares/strict-transport-security/index' {
  declare module.exports: $Exports<'helmet/dist/middlewares/strict-transport-security'>;
}
declare module 'helmet/dist/middlewares/strict-transport-security/index.js' {
  declare module.exports: $Exports<'helmet/dist/middlewares/strict-transport-security'>;
}
declare module 'helmet/dist/middlewares/x-content-type-options/index' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-content-type-options'>;
}
declare module 'helmet/dist/middlewares/x-content-type-options/index.js' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-content-type-options'>;
}
declare module 'helmet/dist/middlewares/x-dns-prefetch-control/index' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-dns-prefetch-control'>;
}
declare module 'helmet/dist/middlewares/x-dns-prefetch-control/index.js' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-dns-prefetch-control'>;
}
declare module 'helmet/dist/middlewares/x-download-options/index' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-download-options'>;
}
declare module 'helmet/dist/middlewares/x-download-options/index.js' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-download-options'>;
}
declare module 'helmet/dist/middlewares/x-frame-options/index' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-frame-options'>;
}
declare module 'helmet/dist/middlewares/x-frame-options/index.js' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-frame-options'>;
}
declare module 'helmet/dist/middlewares/x-permitted-cross-domain-policies/index' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-permitted-cross-domain-policies'>;
}
declare module 'helmet/dist/middlewares/x-permitted-cross-domain-policies/index.js' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-permitted-cross-domain-policies'>;
}
declare module 'helmet/dist/middlewares/x-powered-by/index' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-powered-by'>;
}
declare module 'helmet/dist/middlewares/x-powered-by/index.js' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-powered-by'>;
}
declare module 'helmet/dist/middlewares/x-xss-protection/index' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-xss-protection'>;
}
declare module 'helmet/dist/middlewares/x-xss-protection/index.js' {
  declare module.exports: $Exports<'helmet/dist/middlewares/x-xss-protection'>;
}
