// flow-typed signature: ef905a3a89d98934e5ebb1dbff931717
// flow-typed version: <<STUB>>/moment-locales-webpack-plugin_v^1.2.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-locales-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-locales-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moment-locales-webpack-plugin/jest.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moment-locales-webpack-plugin/index' {
  declare module.exports: $Exports<'moment-locales-webpack-plugin'>;
}
declare module 'moment-locales-webpack-plugin/index.js' {
  declare module.exports: $Exports<'moment-locales-webpack-plugin'>;
}
declare module 'moment-locales-webpack-plugin/jest.config.js' {
  declare module.exports: $Exports<'moment-locales-webpack-plugin/jest.config'>;
}
