// flow-typed signature: 194f3b61086af059e840fd1adddd3672
// flow-typed version: <<STUB>>/socket.io-client_v^3.0.1/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socket.io-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'socket.io-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'socket.io-client/build/index-test' {
  declare module.exports: any;
}

declare module 'socket.io-client/build' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/manager' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/on' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/socket' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/url' {
  declare module.exports: any;
}

declare module 'socket.io-client/dist/socket.io' {
  declare module.exports: any;
}

declare module 'socket.io-client/dist/socket.io.min' {
  declare module.exports: any;
}

declare module 'socket.io-client/dist/socket.io.msgpack.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'socket.io-client/build/index-test.js' {
  declare module.exports: $Exports<'socket.io-client/build/index-test'>;
}
declare module 'socket.io-client/build/index' {
  declare module.exports: $Exports<'socket.io-client/build'>;
}
declare module 'socket.io-client/build/index.js' {
  declare module.exports: $Exports<'socket.io-client/build'>;
}
declare module 'socket.io-client/build/manager.js' {
  declare module.exports: $Exports<'socket.io-client/build/manager'>;
}
declare module 'socket.io-client/build/on.js' {
  declare module.exports: $Exports<'socket.io-client/build/on'>;
}
declare module 'socket.io-client/build/socket.js' {
  declare module.exports: $Exports<'socket.io-client/build/socket'>;
}
declare module 'socket.io-client/build/url.js' {
  declare module.exports: $Exports<'socket.io-client/build/url'>;
}
declare module 'socket.io-client/dist/socket.io.js' {
  declare module.exports: $Exports<'socket.io-client/dist/socket.io'>;
}
declare module 'socket.io-client/dist/socket.io.min.js' {
  declare module.exports: $Exports<'socket.io-client/dist/socket.io.min'>;
}
declare module 'socket.io-client/dist/socket.io.msgpack.min.js' {
  declare module.exports: $Exports<'socket.io-client/dist/socket.io.msgpack.min'>;
}
