// flow-typed signature: c6e36cee4c116da1af477230d50544f6
// flow-typed version: <<STUB>>/@stryker-mutator/core_v^4.1.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@stryker-mutator/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@stryker-mutator/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@stryker-mutator/core/src/checker/checker-facade' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/checker/checker-worker' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/child-proxy/child-process-crashed-error' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/child-proxy/child-process-proxy-worker' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/child-proxy/child-process-proxy' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/child-proxy/message-protocol' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/child-proxy/out-of-memory-error' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/concurrent/concurrency-token-provider' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/concurrent' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/concurrent/pool' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/config/build-schema-with-plugin-contributions' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/config/config-reader' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/config/create-config' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/config' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/config/options-validator' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/config/read-config' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/config/validation-errors' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/di/build-child-process-injector' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/di/build-main-injector' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/di/core-tokens' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/di/factory-methods' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/di' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/di/plugin-creator' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/di/plugin-loader' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/di/provide-logger' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/errors' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/choice-type' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/gitignore-writer' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/initializer-tokens' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/npm-client' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/package-info' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/presets/angular-preset' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/presets/preset-configuration' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/presets/preset' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/presets/react-preset' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/presets/vue-js-preset' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/prompt-option' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/stryker-config-writer' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/stryker-initializer' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/stryker-inquirer' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/initializer/stryker-presets' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/input/input-file-collection' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/input/input-file-resolver' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/logging' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/logging/log-configurator' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/logging/log-utils' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/logging/logging-client-context' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/logging/multi-appender' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/mutants/find-mutant-test-coverage' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/mutants' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/process/1-prepare-executor' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/process/2-mutant-instrumenter-executor' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/process/3-dry-run-executor' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/process/4-mutation-test-executor' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/process' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/broadcast-reporter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/ci/circle-provider' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/ci/github-actions-provider' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/ci/provider' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/ci/travis-provider' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/clear-text-reporter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/clear-text-score-table' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/dashboard-reporter/dashboard-reporter-client' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/dashboard-reporter/dashboard-reporter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/dashboard-reporter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/dashboard-reporter/report' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/dashboard-reporter/tokens' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/dots-reporter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/event-recorder-reporter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/html/html-reporter-util' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/html/html-reporter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/html/templates/bind-mutation-test-report' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/mutation-test-report-helper' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/progress-append-only-reporter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/progress-bar' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/progress-keeper' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/progress-reporter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/reporters/strict-reporter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/sandbox/create-preprocessor' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/sandbox/disable-type-checks-preprocessor' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/sandbox/file-preprocessor' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/sandbox' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/sandbox/multi-preprocessor' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/sandbox/sandbox' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/sandbox/ts-config-preprocessor' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/stryker-cli' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/stryker' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/test-runner/child-process-test-runner-decorator' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/test-runner/child-process-test-runner-worker' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/test-runner/command-test-runner' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/test-runner' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/test-runner/max-test-runner-reuse-decorator' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/test-runner/retry-decorator' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/test-runner/test-runner-decorator' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/test-runner/timeout-decorator' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/utils/file-utils' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/utils/mutant-utils' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/utils/net-utils' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/utils/object-utils' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/utils/string-builder' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/utils/temporary-directory' {
  declare module.exports: any;
}

declare module '@stryker-mutator/core/src/utils/timer' {
  declare module.exports: any;
}

// Filename aliases
declare module '@stryker-mutator/core/src/checker/checker-facade.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/checker/checker-facade'>;
}
declare module '@stryker-mutator/core/src/checker/checker-worker.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/checker/checker-worker'>;
}
declare module '@stryker-mutator/core/src/child-proxy/child-process-crashed-error.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/child-proxy/child-process-crashed-error'>;
}
declare module '@stryker-mutator/core/src/child-proxy/child-process-proxy-worker.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/child-proxy/child-process-proxy-worker'>;
}
declare module '@stryker-mutator/core/src/child-proxy/child-process-proxy.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/child-proxy/child-process-proxy'>;
}
declare module '@stryker-mutator/core/src/child-proxy/message-protocol.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/child-proxy/message-protocol'>;
}
declare module '@stryker-mutator/core/src/child-proxy/out-of-memory-error.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/child-proxy/out-of-memory-error'>;
}
declare module '@stryker-mutator/core/src/concurrent/concurrency-token-provider.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/concurrent/concurrency-token-provider'>;
}
declare module '@stryker-mutator/core/src/concurrent/index' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/concurrent'>;
}
declare module '@stryker-mutator/core/src/concurrent/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/concurrent'>;
}
declare module '@stryker-mutator/core/src/concurrent/pool.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/concurrent/pool'>;
}
declare module '@stryker-mutator/core/src/config/build-schema-with-plugin-contributions.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/config/build-schema-with-plugin-contributions'>;
}
declare module '@stryker-mutator/core/src/config/config-reader.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/config/config-reader'>;
}
declare module '@stryker-mutator/core/src/config/create-config.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/config/create-config'>;
}
declare module '@stryker-mutator/core/src/config/index' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/config'>;
}
declare module '@stryker-mutator/core/src/config/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/config'>;
}
declare module '@stryker-mutator/core/src/config/options-validator.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/config/options-validator'>;
}
declare module '@stryker-mutator/core/src/config/read-config.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/config/read-config'>;
}
declare module '@stryker-mutator/core/src/config/validation-errors.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/config/validation-errors'>;
}
declare module '@stryker-mutator/core/src/di/build-child-process-injector.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/di/build-child-process-injector'>;
}
declare module '@stryker-mutator/core/src/di/build-main-injector.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/di/build-main-injector'>;
}
declare module '@stryker-mutator/core/src/di/core-tokens.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/di/core-tokens'>;
}
declare module '@stryker-mutator/core/src/di/factory-methods.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/di/factory-methods'>;
}
declare module '@stryker-mutator/core/src/di/index' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/di'>;
}
declare module '@stryker-mutator/core/src/di/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/di'>;
}
declare module '@stryker-mutator/core/src/di/plugin-creator.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/di/plugin-creator'>;
}
declare module '@stryker-mutator/core/src/di/plugin-loader.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/di/plugin-loader'>;
}
declare module '@stryker-mutator/core/src/di/provide-logger.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/di/provide-logger'>;
}
declare module '@stryker-mutator/core/src/errors.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/errors'>;
}
declare module '@stryker-mutator/core/src/index' {
  declare module.exports: $Exports<'@stryker-mutator/core/src'>;
}
declare module '@stryker-mutator/core/src/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src'>;
}
declare module '@stryker-mutator/core/src/initializer/choice-type.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/choice-type'>;
}
declare module '@stryker-mutator/core/src/initializer/gitignore-writer.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/gitignore-writer'>;
}
declare module '@stryker-mutator/core/src/initializer/index' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer'>;
}
declare module '@stryker-mutator/core/src/initializer/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer'>;
}
declare module '@stryker-mutator/core/src/initializer/initializer-tokens.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/initializer-tokens'>;
}
declare module '@stryker-mutator/core/src/initializer/npm-client.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/npm-client'>;
}
declare module '@stryker-mutator/core/src/initializer/package-info.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/package-info'>;
}
declare module '@stryker-mutator/core/src/initializer/presets/angular-preset.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/presets/angular-preset'>;
}
declare module '@stryker-mutator/core/src/initializer/presets/preset-configuration.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/presets/preset-configuration'>;
}
declare module '@stryker-mutator/core/src/initializer/presets/preset.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/presets/preset'>;
}
declare module '@stryker-mutator/core/src/initializer/presets/react-preset.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/presets/react-preset'>;
}
declare module '@stryker-mutator/core/src/initializer/presets/vue-js-preset.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/presets/vue-js-preset'>;
}
declare module '@stryker-mutator/core/src/initializer/prompt-option.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/prompt-option'>;
}
declare module '@stryker-mutator/core/src/initializer/stryker-config-writer.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/stryker-config-writer'>;
}
declare module '@stryker-mutator/core/src/initializer/stryker-initializer.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/stryker-initializer'>;
}
declare module '@stryker-mutator/core/src/initializer/stryker-inquirer.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/stryker-inquirer'>;
}
declare module '@stryker-mutator/core/src/initializer/stryker-presets.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/initializer/stryker-presets'>;
}
declare module '@stryker-mutator/core/src/input/input-file-collection.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/input/input-file-collection'>;
}
declare module '@stryker-mutator/core/src/input/input-file-resolver.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/input/input-file-resolver'>;
}
declare module '@stryker-mutator/core/src/logging/index' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/logging'>;
}
declare module '@stryker-mutator/core/src/logging/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/logging'>;
}
declare module '@stryker-mutator/core/src/logging/log-configurator.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/logging/log-configurator'>;
}
declare module '@stryker-mutator/core/src/logging/log-utils.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/logging/log-utils'>;
}
declare module '@stryker-mutator/core/src/logging/logging-client-context.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/logging/logging-client-context'>;
}
declare module '@stryker-mutator/core/src/logging/multi-appender.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/logging/multi-appender'>;
}
declare module '@stryker-mutator/core/src/mutants/find-mutant-test-coverage.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/mutants/find-mutant-test-coverage'>;
}
declare module '@stryker-mutator/core/src/mutants/index' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/mutants'>;
}
declare module '@stryker-mutator/core/src/mutants/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/mutants'>;
}
declare module '@stryker-mutator/core/src/process/1-prepare-executor.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/process/1-prepare-executor'>;
}
declare module '@stryker-mutator/core/src/process/2-mutant-instrumenter-executor.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/process/2-mutant-instrumenter-executor'>;
}
declare module '@stryker-mutator/core/src/process/3-dry-run-executor.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/process/3-dry-run-executor'>;
}
declare module '@stryker-mutator/core/src/process/4-mutation-test-executor.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/process/4-mutation-test-executor'>;
}
declare module '@stryker-mutator/core/src/process/index' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/process'>;
}
declare module '@stryker-mutator/core/src/process/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/process'>;
}
declare module '@stryker-mutator/core/src/reporters/broadcast-reporter.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/broadcast-reporter'>;
}
declare module '@stryker-mutator/core/src/reporters/ci/circle-provider.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/ci/circle-provider'>;
}
declare module '@stryker-mutator/core/src/reporters/ci/github-actions-provider.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/ci/github-actions-provider'>;
}
declare module '@stryker-mutator/core/src/reporters/ci/provider.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/ci/provider'>;
}
declare module '@stryker-mutator/core/src/reporters/ci/travis-provider.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/ci/travis-provider'>;
}
declare module '@stryker-mutator/core/src/reporters/clear-text-reporter.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/clear-text-reporter'>;
}
declare module '@stryker-mutator/core/src/reporters/clear-text-score-table.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/clear-text-score-table'>;
}
declare module '@stryker-mutator/core/src/reporters/dashboard-reporter/dashboard-reporter-client.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/dashboard-reporter/dashboard-reporter-client'>;
}
declare module '@stryker-mutator/core/src/reporters/dashboard-reporter/dashboard-reporter.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/dashboard-reporter/dashboard-reporter'>;
}
declare module '@stryker-mutator/core/src/reporters/dashboard-reporter/index' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/dashboard-reporter'>;
}
declare module '@stryker-mutator/core/src/reporters/dashboard-reporter/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/dashboard-reporter'>;
}
declare module '@stryker-mutator/core/src/reporters/dashboard-reporter/report.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/dashboard-reporter/report'>;
}
declare module '@stryker-mutator/core/src/reporters/dashboard-reporter/tokens.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/dashboard-reporter/tokens'>;
}
declare module '@stryker-mutator/core/src/reporters/dots-reporter.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/dots-reporter'>;
}
declare module '@stryker-mutator/core/src/reporters/event-recorder-reporter.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/event-recorder-reporter'>;
}
declare module '@stryker-mutator/core/src/reporters/html/html-reporter-util.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/html/html-reporter-util'>;
}
declare module '@stryker-mutator/core/src/reporters/html/html-reporter.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/html/html-reporter'>;
}
declare module '@stryker-mutator/core/src/reporters/html/templates/bind-mutation-test-report.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/html/templates/bind-mutation-test-report'>;
}
declare module '@stryker-mutator/core/src/reporters/index' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters'>;
}
declare module '@stryker-mutator/core/src/reporters/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters'>;
}
declare module '@stryker-mutator/core/src/reporters/mutation-test-report-helper.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/mutation-test-report-helper'>;
}
declare module '@stryker-mutator/core/src/reporters/progress-append-only-reporter.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/progress-append-only-reporter'>;
}
declare module '@stryker-mutator/core/src/reporters/progress-bar.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/progress-bar'>;
}
declare module '@stryker-mutator/core/src/reporters/progress-keeper.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/progress-keeper'>;
}
declare module '@stryker-mutator/core/src/reporters/progress-reporter.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/progress-reporter'>;
}
declare module '@stryker-mutator/core/src/reporters/strict-reporter.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/reporters/strict-reporter'>;
}
declare module '@stryker-mutator/core/src/sandbox/create-preprocessor.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/sandbox/create-preprocessor'>;
}
declare module '@stryker-mutator/core/src/sandbox/disable-type-checks-preprocessor.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/sandbox/disable-type-checks-preprocessor'>;
}
declare module '@stryker-mutator/core/src/sandbox/file-preprocessor.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/sandbox/file-preprocessor'>;
}
declare module '@stryker-mutator/core/src/sandbox/index' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/sandbox'>;
}
declare module '@stryker-mutator/core/src/sandbox/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/sandbox'>;
}
declare module '@stryker-mutator/core/src/sandbox/multi-preprocessor.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/sandbox/multi-preprocessor'>;
}
declare module '@stryker-mutator/core/src/sandbox/sandbox.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/sandbox/sandbox'>;
}
declare module '@stryker-mutator/core/src/sandbox/ts-config-preprocessor.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/sandbox/ts-config-preprocessor'>;
}
declare module '@stryker-mutator/core/src/stryker-cli.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/stryker-cli'>;
}
declare module '@stryker-mutator/core/src/stryker.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/stryker'>;
}
declare module '@stryker-mutator/core/src/test-runner/child-process-test-runner-decorator.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/test-runner/child-process-test-runner-decorator'>;
}
declare module '@stryker-mutator/core/src/test-runner/child-process-test-runner-worker.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/test-runner/child-process-test-runner-worker'>;
}
declare module '@stryker-mutator/core/src/test-runner/command-test-runner.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/test-runner/command-test-runner'>;
}
declare module '@stryker-mutator/core/src/test-runner/index' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/test-runner'>;
}
declare module '@stryker-mutator/core/src/test-runner/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/test-runner'>;
}
declare module '@stryker-mutator/core/src/test-runner/max-test-runner-reuse-decorator.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/test-runner/max-test-runner-reuse-decorator'>;
}
declare module '@stryker-mutator/core/src/test-runner/retry-decorator.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/test-runner/retry-decorator'>;
}
declare module '@stryker-mutator/core/src/test-runner/test-runner-decorator.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/test-runner/test-runner-decorator'>;
}
declare module '@stryker-mutator/core/src/test-runner/timeout-decorator.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/test-runner/timeout-decorator'>;
}
declare module '@stryker-mutator/core/src/utils/file-utils.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/utils/file-utils'>;
}
declare module '@stryker-mutator/core/src/utils/mutant-utils.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/utils/mutant-utils'>;
}
declare module '@stryker-mutator/core/src/utils/net-utils.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/utils/net-utils'>;
}
declare module '@stryker-mutator/core/src/utils/object-utils.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/utils/object-utils'>;
}
declare module '@stryker-mutator/core/src/utils/string-builder.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/utils/string-builder'>;
}
declare module '@stryker-mutator/core/src/utils/temporary-directory.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/utils/temporary-directory'>;
}
declare module '@stryker-mutator/core/src/utils/timer.js' {
  declare module.exports: $Exports<'@stryker-mutator/core/src/utils/timer'>;
}
