// flow-typed signature: f012b20953fe628217096127449890ef
// flow-typed version: <<STUB>>/@stryker-mutator/jest-runner_v^4.1.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@stryker-mutator/jest-runner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@stryker-mutator/jest-runner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@stryker-mutator/jest-runner/src/config-loaders/custom-jest-config-loader' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/config-loaders' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/config-loaders/jest-config-loader' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/config-loaders/node-require-function' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/config-loaders/react-scripts-jest-config-loader' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/config-loaders/react-scripts-ts-jest-config-loader' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/jest-override-options' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/jest-run-result' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/jest-runner-options-with-stryker-options' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/jest-test-adapters' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/jest-test-adapters/jest-greater-than-25-adapter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/jest-test-adapters/jest-less-than-25-adapter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/jest-test-adapters/jest-test-adapter' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/jest-test-runner' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/plugin-tokens' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/utils/create-react-jest-config' {
  declare module.exports: any;
}

declare module '@stryker-mutator/jest-runner/src/utils/jest-wrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module '@stryker-mutator/jest-runner/src/config-loaders/custom-jest-config-loader.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/config-loaders/custom-jest-config-loader'>;
}
declare module '@stryker-mutator/jest-runner/src/config-loaders/index' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/config-loaders'>;
}
declare module '@stryker-mutator/jest-runner/src/config-loaders/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/config-loaders'>;
}
declare module '@stryker-mutator/jest-runner/src/config-loaders/jest-config-loader.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/config-loaders/jest-config-loader'>;
}
declare module '@stryker-mutator/jest-runner/src/config-loaders/node-require-function.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/config-loaders/node-require-function'>;
}
declare module '@stryker-mutator/jest-runner/src/config-loaders/react-scripts-jest-config-loader.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/config-loaders/react-scripts-jest-config-loader'>;
}
declare module '@stryker-mutator/jest-runner/src/config-loaders/react-scripts-ts-jest-config-loader.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/config-loaders/react-scripts-ts-jest-config-loader'>;
}
declare module '@stryker-mutator/jest-runner/src/index' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src'>;
}
declare module '@stryker-mutator/jest-runner/src/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src'>;
}
declare module '@stryker-mutator/jest-runner/src/jest-override-options.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/jest-override-options'>;
}
declare module '@stryker-mutator/jest-runner/src/jest-run-result.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/jest-run-result'>;
}
declare module '@stryker-mutator/jest-runner/src/jest-runner-options-with-stryker-options.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/jest-runner-options-with-stryker-options'>;
}
declare module '@stryker-mutator/jest-runner/src/jest-test-adapters/index' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/jest-test-adapters'>;
}
declare module '@stryker-mutator/jest-runner/src/jest-test-adapters/index.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/jest-test-adapters'>;
}
declare module '@stryker-mutator/jest-runner/src/jest-test-adapters/jest-greater-than-25-adapter.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/jest-test-adapters/jest-greater-than-25-adapter'>;
}
declare module '@stryker-mutator/jest-runner/src/jest-test-adapters/jest-less-than-25-adapter.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/jest-test-adapters/jest-less-than-25-adapter'>;
}
declare module '@stryker-mutator/jest-runner/src/jest-test-adapters/jest-test-adapter.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/jest-test-adapters/jest-test-adapter'>;
}
declare module '@stryker-mutator/jest-runner/src/jest-test-runner.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/jest-test-runner'>;
}
declare module '@stryker-mutator/jest-runner/src/plugin-tokens.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/plugin-tokens'>;
}
declare module '@stryker-mutator/jest-runner/src/utils/create-react-jest-config.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/utils/create-react-jest-config'>;
}
declare module '@stryker-mutator/jest-runner/src/utils/jest-wrapper.js' {
  declare module.exports: $Exports<'@stryker-mutator/jest-runner/src/utils/jest-wrapper'>;
}
