// flow-typed signature: ccbf387aa3bfde7fe42736cdbe819729
// flow-typed version: <<STUB>>/@babel/plugin-transform-arrow-functions_v^7.12.1/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-arrow-functions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-arrow-functions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-arrow-functions/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-arrow-functions/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-arrow-functions/lib'>;
}
declare module '@babel/plugin-transform-arrow-functions/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-arrow-functions/lib'>;
}
